name: Unit Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run sum.test.js
        run: npm test ./__tests__/sum.test.js

      - name: Run unit.test.js
        run: npm test ./__tests__/unit.test.js
